/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pbo.Dosen;
import pbo.Kelas;
import pbo.Mahasiswa;
import pbo.Matkul;

/**
 *
 * @author ASUS
 */
public class AdminMenu extends javax.swing.JPanel {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMahasiswa = new javax.swing.JTable();
        buttonDeleteMhs = new javax.swing.JButton();
        buttonEditMhs = new javax.swing.JButton();
        txtNim = new javax.swing.JTextField();
        txtNamaMhs = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        buttonSubmitMhs = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();
        buttonDeleteDsn = new javax.swing.JButton();
        buttonSubmitDsn = new javax.swing.JButton();
        buttonEditDsn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNip = new javax.swing.JTextField();
        txtNamaDsn = new javax.swing.JTextField();
        txtKodeDosen = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        buttonEditMK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtKodeMK = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNamaMK = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableMK = new javax.swing.JTable();
        buttonDeleteMK = new javax.swing.JButton();
        buttonSubmitMK = new javax.swing.JButton();
        spinSKS = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        buttonEditKls = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtKodeKls = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Dosen = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableKelas = new javax.swing.JTable();
        buttonDeleteKls = new javax.swing.JButton();
        buttonSubmitKls = new javax.swing.JButton();
        cbDosenKelas = new javax.swing.JComboBox();
        cbMKKelas = new javax.swing.JComboBox();

        jScrollPane1.setViewportView(jEditorPane1);

        tableMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableMahasiswa);

        buttonDeleteMhs.setText("Delete");

        buttonEditMhs.setText("Edit");

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        buttonSubmitMhs.setText("Submit");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kelola Mahasiswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEditMhs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteMhs))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNim)
                                    .addComponent(txtNamaMhs)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSubmitMhs))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteMhs)
                    .addComponent(buttonEditMhs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmitMhs)
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kelola Mahasiswa", jPanel1);

        jLabel6.setText("NIP");

        jLabel7.setText("Nama");

        jLabel8.setText("Kode");

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableDosen);

        buttonDeleteDsn.setText("Delete");

        buttonSubmitDsn.setText("Submit");

        buttonEditDsn.setText("Edit");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Kelola Dosen");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEditDsn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteDsn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNip)
                                    .addComponent(txtNamaDsn)
                                    .addComponent(txtKodeDosen, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSubmitDsn))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteDsn)
                    .addComponent(buttonEditDsn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaDsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmitDsn)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kelola Dosen", jPanel2);

        buttonEditMK.setText("Edit");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Kelola Mata Kuliah");

        jLabel9.setText("Kode");

        jLabel12.setText("Nama");

        jLabel13.setText("SKS");

        tableMK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tableMK);

        buttonDeleteMK.setText("Delete");

        buttonSubmitMK.setText("Submit");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEditMK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteMK))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeMK)
                                    .addComponent(txtNamaMK)
                                    .addComponent(spinSKS)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSubmitMK))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteMK)
                    .addComponent(buttonEditMK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(spinSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmitMK)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kelola Mata Kuliah", jPanel3);

        buttonEditKls.setText("Edit");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Kelola Mata Kuliah");

        jLabel15.setText("Kode");

        Dosen.setText("Dosen");

        jLabel17.setText("Mata Kuliah");

        tableKelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableKelas);

        buttonDeleteKls.setText("Delete");

        buttonSubmitKls.setText("Submit");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonEditKls)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDeleteKls))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Dosen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKodeKls)
                                    .addComponent(cbDosenKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbMKKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonSubmitKls))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 145, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDeleteKls)
                    .addComponent(buttonEditKls))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(57, 57, 57)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKodeKls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dosen)
                            .addComponent(cbDosenKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cbMKKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSubmitKls)
                        .addGap(0, 134, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Kelola Kelas", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dosen;
    private javax.swing.JButton buttonDeleteDsn;
    private javax.swing.JButton buttonDeleteKls;
    private javax.swing.JButton buttonDeleteMK;
    private javax.swing.JButton buttonDeleteMhs;
    private javax.swing.JButton buttonEditDsn;
    private javax.swing.JButton buttonEditKls;
    private javax.swing.JButton buttonEditMK;
    private javax.swing.JButton buttonEditMhs;
    private javax.swing.JButton buttonSubmitDsn;
    private javax.swing.JButton buttonSubmitKls;
    private javax.swing.JButton buttonSubmitMK;
    private javax.swing.JButton buttonSubmitMhs;
    private javax.swing.JComboBox cbDosenKelas;
    private javax.swing.JComboBox cbMKKelas;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner spinSKS;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTable tableKelas;
    private javax.swing.JTable tableMK;
    private javax.swing.JTable tableMahasiswa;
    private javax.swing.JTextField txtKodeDosen;
    private javax.swing.JTextField txtKodeKls;
    private javax.swing.JTextField txtKodeMK;
    private javax.swing.JTextField txtNamaDsn;
    private javax.swing.JTextField txtNamaMK;
    private javax.swing.JTextField txtNamaMhs;
    private javax.swing.JTextField txtNim;
    private javax.swing.JTextField txtNip;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    //================================================ TAB KELOLA MAHASISWA ===================================================//
    
    public int getNimMhs(){
        return Integer.parseInt(txtNim.getText());
    }
    
    public String getNamaMhs(){
        return txtNamaMhs.getText();
    }
    
    public String getUsername(){
        return txtUsername.getText();
    }
    
    public String getPassword(){
        return txtPassword.getText();
    }
    
    public Object getSubmitMhs(){
        return buttonSubmitMhs;
    }
    
    public Object getEditMhs(){
        return buttonEditMhs;
    }
    
    public Object getDeleteMhs(){
        return buttonDeleteMhs;
    }
    
    public Object getDaftarMhs(){
        return tableMahasiswa;
    }
    
    public void setTableMahasiswa(ArrayList<Mahasiswa> list){
        String[] judul = {"NIM","Nama","Username","Password"};
        String[][] isi = new String[list.size()][4];
        int i = 0;
        for (Mahasiswa m : list){
            isi[i][0] = String.valueOf(m.getNim());
            isi[i][1] = m.getNama();
            isi[i][2] = m.getUsername();
            isi[i][3] = m.getPassword();
            i++;
        }
        DefaultTableModel tablemodel = new DefaultTableModel(isi,judul);
        tableMahasiswa.setModel(tablemodel);
        tableMahasiswa.getColumnModel().getColumn(0).setPreferredWidth(20);
    }
    
    public int getSelectedMhs(){
        return tableMahasiswa.getSelectedRow();
    }
    
    public void refreshMhs(){
        txtNim.setText("");
        txtNamaMhs.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
    }
    
    public void refreshEditMhs(Mahasiswa m){
        txtNim.setText(String.valueOf(m.getNim()));
        txtNamaMhs.setText(m.getNama());
        txtUsername.setText(m.getUsername());
        txtPassword.setText(m.getPassword());
    }
    
    //============================================= END OF TAB KELOLA MAHASISWA ===============================================//
    
    //================================================== TAB KELOLA DOSEN =====================================================//
    
    public int getNip(){
        return Integer.parseInt(txtNip.getText());
    }
    
    public String getNamaDosen(){
        return txtNamaDsn.getText();
    }
    
    public String getKodeDosen(){
        return txtKodeDosen.getText();
    }
    
    public Object getSubmitDsn(){
        return buttonSubmitDsn;
    }
    
    public Object getEditDsn(){
        return buttonEditDsn;
    }
    
    public Object getDeleteDsn(){
        return buttonDeleteDsn;
    }
    
    public Object getDaftarDsn(){
        return tableDosen;
    }
    
    public void setTableDosen(ArrayList<Dosen> list){
        String[] judul = {"NIP","Nama","Kode Dosen"};
        String[][] isi = new String[list.size()][3];
        int i = 0;
        for (Dosen m : list){
            isi[i][0] = String.valueOf(m.getNip());
            isi[i][1] = m.getNama();
            isi[i][2] = m.getKD();
            i++;
        }
        DefaultTableModel tablemodel = new DefaultTableModel(isi,judul);
        tableDosen.setModel(tablemodel);
        tableDosen.getColumnModel().getColumn(0).setPreferredWidth(20);
    }
    
    public int getSelectedDsn(){
        return tableDosen.getSelectedRow();
    }
    
    public void refreshDsn(){
        txtNip.setText("");
        txtNamaDsn.setText("");
        txtKodeDosen.setText("");
    }
    
    public void refreshEditDsn(Dosen m){
        txtNip.setText(String.valueOf(m.getNip()));
        txtNamaDsn.setText(m.getNama());
        txtKodeDosen.setText(m.getKD());
    }
    
    //============================================= END OF TAB KELOLA DOSEN ===============================================//

    //================================================== TAB KELOLA MK =====================================================//
    
    public String getKodeMK(){
        return txtKodeMK.getText();
    }
    
    public String getNamaMK(){
        return txtNamaMK.getText();
    }
    
    public int getSKS(){
        return (Integer) spinSKS.getValue();
    }
    
    public Object getSubmitMK(){
        return buttonSubmitMK;
    }
    
    public Object getEditMK(){
        return buttonEditMK;
    }
    
    public Object getDeleteMK(){
        return buttonDeleteMK;
    }
    
    public Object getDaftarMK(){
        return tableMK;
    }
    
    public void setTableMK(ArrayList<Matkul> list){
        String[] judul = {"Kode MK","Nama MK","SKS"};
        String[][] isi = new String[list.size()][3];
        int i = 0;
        for (Matkul m : list){
            isi[i][0] = m.getKodeMK();
            isi[i][1] = m.getNamaMK();
            isi[i][2] = String.valueOf(m.getSks());
            i++;
        }
        DefaultTableModel tablemodel = new DefaultTableModel(isi,judul);
        tableMK.setModel(tablemodel);
        tableMK.getColumnModel().getColumn(0).setPreferredWidth(20);
    }
    
    public int getSelectedMK(){
        return tableMK.getSelectedRow();
    }
    
    public void refreshMK(){
        txtKodeMK.setText("");
        txtNamaMK.setText("");
        spinSKS.setValue(0);
    }
    
    public void refreshEditMK(Matkul m){
        txtKodeMK.setText(m.getKodeMK());
        txtNamaMK.setText(m.getNamaMK());
        spinSKS.setValue(m.getSks());
    }
    
    //=============================================== END OF TAB KELOLA MK ====================================================//
    
    //================================================= TAB KELOLA KELAS =====================================================//
    
    public String getKodeKls(){
        return txtKodeKls.getText();
    }
    
    public String getDosenKelas(){
        return (String) cbDosenKelas.getSelectedItem();
    }
    
    public void setDosenKelas(String[] list){
        for (String i : list){
            cbDosenKelas.addItem(i);
        }
    }
    
    public void setDosenKelasNull(String[] list){
        for (String i : list){
            cbDosenKelas.removeItem(i);
        }
    }
    
    public void addDosenKelas(String kode){
        cbDosenKelas.addItem(kode);
    }
    
    public void deleteDosenKelas(String kode){
        cbDosenKelas.removeItem(kode);
    }
    
    public String getMKKelas(){
        return (String) cbMKKelas.getSelectedItem();
    }
    
    public void setMKKelas(String[] list){
        for (String i : list){
            cbMKKelas.addItem(i);
        }
    }
    
    public void setMKKelasNull(String[] list){
        for (String i : list){
            cbMKKelas.removeItem(i);
        }
    }
    
    public void addMKKelas(String kode){
        cbMKKelas.addItem(kode);
    }
    
    public void deleteMKKelas(String kode){
        cbMKKelas.removeItem(kode);
    }
    
    public Object getSubmitKls(){
        return buttonSubmitKls;
    }
    
    public Object getEditKls(){
        return buttonEditKls;
    }
    
    public Object getDeleteKls(){
        return buttonDeleteKls;
    }
    
    public Object getDaftarKls(){
        return tableKelas;
    }
    
    public void setTableKls(ArrayList<Kelas> list){
        String[] judul = {"Kode Kelas","Kode MK","Kode Dosen"};
        String[][] isi = new String[list.size()][3];
        int i = 0;
        for (Kelas m : list){
            isi[i][0] = String.valueOf(m.getIdk());
            isi[i][1] = m.getMatkul().getKodeMK();
            isi[i][2] = m.getDosen().getKD();
            i++;
        }
        DefaultTableModel tablemodel = new DefaultTableModel(isi,judul);
        tableKelas.setModel(tablemodel);
        tableKelas.getColumnModel().getColumn(0).setPreferredWidth(20);
    }
    
    public int getSelectedKls(){
        return tableKelas.getSelectedRow();
    }
    
    public void refreshKls(){
        txtKodeKls.setText("");
        cbDosenKelas.setSelectedIndex(0);
        cbMKKelas.setSelectedIndex(0);
    }
    
    public void refreshEditKelas(Kelas m){
        txtKodeMK.setText(String.valueOf(m.getIdk()));
        cbDosenKelas.setSelectedItem(m.getDosen().getKD());
        cbMKKelas.setSelectedItem(m.getMatkul().getKodeMK());
    }
    
    //============================================= END OF TAB KELOLA KELAS ==================================================//
    
    public void addListener(ActionListener e){
        buttonSubmitMhs.addActionListener(e);
        buttonSubmitDsn.addActionListener(e);
        buttonSubmitMK.addActionListener(e);
        buttonSubmitKls.addActionListener(e);
        buttonEditMhs.addActionListener(e);
        buttonEditDsn.addActionListener(e);
        buttonEditMK.addActionListener(e);
        buttonEditKls.addActionListener(e);
        buttonDeleteMhs.addActionListener(e);
        buttonDeleteDsn.addActionListener(e);
        buttonDeleteMK.addActionListener(e);
        buttonDeleteKls.addActionListener(e);
    }
    
    public void addAdapter(MouseAdapter e){
        tableMahasiswa.addMouseListener(e);
        tableDosen.addMouseListener(e);
        tableMK.addMouseListener(e);
        tableKelas.addMouseListener(e);
    }
    
    
}
